name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install latest nightly
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Check formatting
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo fmt -- --check
    - name: Run linting
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo clippy
    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo build --verbose
    - name: Run tests
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo test --verbose
